project_structure:
    build: build
    contracts: contracts
    interfaces: interfaces
    reports: reports
    scripts: scripts
    tests: tests

networks:
    default: development
    development:
        
        name: Fantom Mainnet Fork
        cmd: ganache-cli
        cmd_settings:
          fork: wss://wsapi.fantom.network
          accounts: 5
          evm_version: istanbul
          gas_limit: 12000000
          mnemonic: brownie
          port: 8545
          chain_id: 250
          default_balance: "1000 ether"
        host: http://127.0.0.1
        id: ftm-fork
        explorer: https://api.ftmscan.com/api
    live:
        gas_limit: auto
        gas_buffer: 1.1
        gas_price: auto
        max_fee: null
        priority_fee: null
        reverting_tx_gas_limit: false
        default_contract_owner: false

compiler:
    evm_version: null
    solc:
        version: null
        optimizer:
            enabled: true
            runs: 200
        remappings:
            - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@2.5.1"
            - "@uniswap/v2-core=uniswap/uniswap-v2-core@1.0.1"
            - "@uniswap/lib=uniswap/uniswap-lib@2.1.0"
            - "@uniswap/v2-periphery=uniswap/v2-periphery@1.0.0-beta.0"
    vyper:
        version: null

console:
    show_colors: true
    color_style: monokai
    auto_suggest: true
    completions: true
    editing_mode: emacs

reports:
    exclude_paths: null
    exclude_contracts: null
    only_include_project: true

hypothesis:
    deadline: null
    max_examples: 50
    report_multiple_bugs: true
    stateful_step_count: 10
    phases:
        explicit: true
        reuse: true
        generate: true
        target: true
        shrink: true

autofetch_sources: false
dependencies: null
dev_deployment_artifacts: false
